drop table if exists subtask_domain CASCADE ;
drop table if exists task_domain CASCADE; 
create table subtask_domain (id bigint generated by default as identity, done boolean, effort_level integer, subtask_description varchar(255), my_task_id bigint, primary key (id));
create table task_domain (id bigint generated by default as identity, task_name varchar(255), primary key (id));
alter table subtask_domain add constraint FK8ayquxamghxk52o7v7f40uh8r foreign key (my_task_id) references task_domain on delete cascade;